# Generated by Django 5.1 on 2024-08-20 22:56

from django.db import migrations

def create_simple_cake_recipe(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    Recipe = apps.get_model('recipes', 'Recipe')
    RecipeIngredient = apps.get_model('recipes', 'RecipeIngredient')

    # RecipeIngredient(recipe=)

    # egg = Ingredient(name="Egg")
    

    Recipe(name="Simple White Cake", description="Easy but delicious cake recipe. Top with your favorite frosting!",
            cook_time_minutes=40, serving_size=12, instructions="These are the instructions.").save()
    Recipe(name="Lavacake", description="An easy cake to make for chocolate lovers!", image="images/simple-cake.png",
        cook_time_minutes=20, serving_size=1, instructions="These are the instructions.").save()
    
def remove_recipes(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    for recipe in Recipe.objects.all():
        recipe.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=create_simple_cake_recipe, reverse_code=remove_recipes),
    ]
