# # Generated by Django 5.1 on 2024-08-23 03:13

# from django.db import migrations

# def create_simple_cake_recipe(apps, schema_editor):
#     Recipe = apps.get_model('recipes', 'Recipe')
#     Ingredient = apps.get_model('recipes', 'Ingredient')
#     Instruction = apps.get_model('recipes', 'Instruction')
#     RecipeIngredient = apps.get_model('recipes', 'RecipeIngredient')

#     carbonara = Recipe(name="Carbonara", description="Carbonara is a simple dish. The quality of your ingredients makes or breaks it. "
#            + "I recommend using the best ingredients you can source. Suggestions: bronze extruded pasta, 24 months aged "
#            + "Parmigiano-Reggiano, 12+ months aged Pecorino Romano, guanciale from the butcher, and organic eggs.",
#             image="images/carbonara.png", cook_time_minutes=30, serving_size=4).save()
#     lavacake = Recipe(name="Lavacake", description="Easily made chocolate dessert with fluid chocolate content. The only requirement is a baking tin with cupcake pits.", 
#            image="images/lavacake.png", cook_time_minutes=22, serving_size=4).save()
#     caesar = Recipe(name="Caesar Salad", description="Caesar Salad is an easy and delicious meal for lunch or dinner.",
#             image="images/caesar-salad.png", cook_time_minutes=10, serving_size=1).save()

#     # Carbonara
#     egg = Ingredient(name="Egg").save()
#     spag_noodles = Ingredient(name="Spaghetti noodles").save()
#     guan_or_panc = Ingredient(name="Guanciale or Smoked Pancetta (cleaned and cubed)").save()
#     peco_or_parm = Ingredient(name="Pecorino Romano or Parmigiano-Reggiano (grated)(optional)").save()

#     # Lavacake (plus egg above)
#     flour = Ingredient(name="Flour").save()
#     butter = Ingredient(name="Butter").save()
#     chocolate = Ingredient(name="Chocolate").save()

#     # Caesar Salad
#     romaine = Ingredient(name="Romaine Lettuce").save()
#     parm = Ingredient(name="Grated Parmesan Cheese").save()
#     croutons = Ingredient(name="Croutons").save()
#     caesar_dressing = Ingredient(name="Caesar Salad Dressing").save()

#     RecipeIngredient(recipe=carbonara, ingredient=spag_noodles, amount="320g | 11oz").save()
#     RecipeIngredient(recipe=carbonara, ingredient=egg, amount="5").save()
#     RecipeIngredient(recipe=carbonara, ingredient=guan_or_panc, amount="150 g | 5 oz").save()
#     RecipeIngredient(recipe=carbonara, ingredient=peco_or_parm, amount="To taste").save()

#     RecipeIngredient(recipe=lavacake, ingredient=egg, amount="1").save()
#     RecipeIngredient(recipe=lavacake, ingredient=flour, amount="25g").save()
#     RecipeIngredient(recipe=lavacake, ingredient=butter, amount="25g").save()
#     RecipeIngredient(recipe=lavacake, ingredient=chocolate, amount="75g").save()

#     RecipeIngredient(recipe=caesar, ingredient=romaine, amount="1 head").save()
#     RecipeIngredient(recipe=caesar, ingredient=parm, amount="To taste").save()
#     RecipeIngredient(recipe=caesar, ingredient=croutons, amount="To taste").save()
#     RecipeIngredient(recipe=caesar, ingredient=caesar_dressing, amount="To taste").save()

#     Instruction(recipe=carbonara, step_number=1, text="Crack the eggs in a bowl but only add the yolks. Add a generous amount of your preferred grated cheese (Pecorino or Parmigiano) around 35g (you can optionally add a dash of black pepper).").save()
#     Instruction(recipe=carbonara, step_number=2, text="Fill a pot with water and salt it less than typical pasta water. When it boils, cook the pasta one minute less than advised.").save()
#     Instruction(recipe=carbonara, step_number=3, text="Fry the preferred pork (Guanciale or Smoked Pancetta) in an iron or nonstick pan (if using a different kind of pan add a dash of extra virgin olive oil) on low to medium heat until the sides are crisp but the insides are chewy.").save()
#     Instruction(recipe=carbonara, step_number=4, text="While everything is being cooked and fried, beat the eggs manually using a fork until everything is entirely liquid. Remember to watch the time.").save()
#     Instruction(recipe=carbonara, step_number=5, text="When your pasta is done (-1 minute), drain it and put it in the bowl with eggs. At this step you may consider the timing: if the pasta is too hot you will cook the eggs, "
#                 + "and some people don’t like it this way, so just wait for a minute. Keep moving and stirring to fully incorporate the eggs. Add guanciale and as many fats remaining in the pan as you want. Keep moving and stirring.").save()
#     Instruction(recipe=carbonara, step_number=6, text="Plate and optionally garnish with the preferred grated cheese and black pepper. Voila.").save()

#     Instruction(recipe=lavacake, step_number=1, text="Cover the baking tin with some butter.").save()
#     Instruction(recipe=lavacake, step_number=2, text="Heat the oven for 200°C.").save()
#     Instruction(recipe=lavacake, step_number=3, text="Mix all of the ingredients.").save()
#     Instruction(recipe=lavacake, step_number=4, text="Fill dough in the baking tins pits.").save()
#     Instruction(recipe=lavacake, step_number=5, text="Bake for 7 min. in the oven at 200°C.").save()
#     Instruction(recipe=lavacake, step_number=6, text="Serve hot with berries and vanilla ice-cream.").save()

#     Instruction(recipe=caesar, step_number=1, text="Prepare a whole head of Romaine Lettuce by chopping off the root and rising thoroughly with water. Dry completely.").save()
#     Instruction(recipe=caesar, step_number=2, text="Once the lettuce is fully dry, put in a mixing bowl with lettuce and the Caesar Salad dressing. Toss to cover each leaf completely.").save()
#     Instruction(recipe=caesar, step_number=3, text="Add croutons.").save()
#     Instruction(recipe=caesar, step_number=4, text="Grate Parmesan over salad.").save()
#     Instruction(recipe=caesar, step_number=5, text="Enjoy!").save()

#     # carbonara.save()
#     # lavacake.save()
#     # caesar.save()


# def remove_recipes(apps, schema_editor):
#     Recipe = apps.get_model('recipes', 'Recipe')
#     for recipe in Recipe.objects.all():
#         recipe.delete()


# class Migration(migrations.Migration):

#     dependencies = [
#         ('recipes', '0001_initial'),
#     ]

#     operations = [
#         migrations.RunPython(code=create_simple_cake_recipe, reverse_code=remove_recipes),
#     ]

from django.db import migrations

def create_simple_cake_recipe(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    Ingredient = apps.get_model('recipes', 'Ingredient')
    Instruction = apps.get_model('recipes', 'Instruction')
    RecipeIngredient = apps.get_model('recipes', 'RecipeIngredient')

    carbonara = Recipe(name="Carbonara", description="Carbonara is a simple dish. The quality of your ingredients makes or breaks it. "
           + "I recommend using the best ingredients you can source. Suggestions: bronze extruded pasta, 24 months aged "
           + "Parmigiano-Reggiano, 12+ months aged Pecorino Romano, guanciale from the butcher, and organic eggs.",
            image="images/carbonara.png", cook_time_minutes=30, serving_size=4)
    carbonara.save()

    lavacake = Recipe(name="Lavacake", description="Easily made chocolate dessert with fluid chocolate content. The only requirement is a baking tin with cupcake pits.", 
           image="images/lavacake.png", cook_time_minutes=22, serving_size=4)
    lavacake.save()

    caesar = Recipe(name="Caesar Salad", description="Caesar Salad is an easy and delicious meal for lunch or dinner.",
            image="images/caesar-salad.png", cook_time_minutes=10, serving_size=1)
    caesar.save()

    # Carbonara
    egg = Ingredient(name="Egg")
    egg.save()

    spag_noodles = Ingredient(name="Spaghetti noodles")
    spag_noodles.save()

    guan_or_panc = Ingredient(name="Guanciale or Smoked Pancetta (cleaned and cubed)")
    guan_or_panc.save()

    peco_or_parm = Ingredient(name="Pecorino Romano or Parmigiano-Reggiano (grated)(optional)")
    peco_or_parm.save()

    # Lavacake (plus egg above)
    flour = Ingredient(name="Flour")
    flour.save()

    butter = Ingredient(name="Butter")
    butter.save()

    chocolate = Ingredient(name="Chocolate")
    chocolate.save()

    # Caesar Salad
    romaine = Ingredient(name="Romaine Lettuce")
    romaine.save()

    parm = Ingredient(name="Grated Parmesan Cheese")
    parm.save()

    croutons = Ingredient(name="Croutons")
    croutons.save()

    caesar_dressing = Ingredient(name="Caesar Salad Dressing")
    caesar_dressing.save()

    # Adding Ingredients to Recipes
    carbonara_ingredients = [
        RecipeIngredient(recipe=carbonara, ingredient=spag_noodles, amount="320g | 11oz"),
        RecipeIngredient(recipe=carbonara, ingredient=egg, amount="5"),
        RecipeIngredient(recipe=carbonara, ingredient=guan_or_panc, amount="150 g | 5 oz"),
        RecipeIngredient(recipe=carbonara, ingredient=peco_or_parm, amount="To taste")
    ]
    for ri in carbonara_ingredients:
        ri.save()
        carbonara.ingredients.add(ri)

    lavacake_ingredients = [
        RecipeIngredient(recipe=lavacake, ingredient=egg, amount="1"),
        RecipeIngredient(recipe=lavacake, ingredient=flour, amount="25g"),
        RecipeIngredient(recipe=lavacake, ingredient=butter, amount="25g"),
        RecipeIngredient(recipe=lavacake, ingredient=chocolate, amount="75g")
    ]
    for ri in lavacake_ingredients:
        ri.save()
        lavacake.ingredients.add(ri)

    caesar_ingredients = [
        RecipeIngredient(recipe=caesar, ingredient=romaine, amount="1 head"),
        RecipeIngredient(recipe=caesar, ingredient=parm, amount="To taste"),
        RecipeIngredient(recipe=caesar, ingredient=croutons, amount="To taste"),
        RecipeIngredient(recipe=caesar, ingredient=caesar_dressing, amount="To taste")
    ]
    for ri in caesar_ingredients:
        ri.save()
        caesar.ingredients.add(ri)

    Instruction(recipe=carbonara, step_number=1, text="Crack the eggs in a bowl but only add the yolks. Add a generous amount of your preferred grated cheese (Pecorino or Parmigiano) around 35g (you can optionally add a dash of black pepper).").save()
    Instruction(recipe=carbonara, step_number=2, text="Fill a pot with water and salt it less than typical pasta water. When it boils, cook the pasta one minute less than advised.").save()
    Instruction(recipe=carbonara, step_number=3, text="Fry the preferred pork (Guanciale or Smoked Pancetta) in an iron or nonstick pan (if using a different kind of pan add a dash of extra virgin olive oil) on low to medium heat until the sides are crisp but the insides are chewy.").save()
    Instruction(recipe=carbonara, step_number=4, text="While everything is being cooked and fried, beat the eggs manually using a fork until everything is entirely liquid. Remember to watch the time.").save()
    Instruction(recipe=carbonara, step_number=5, text="When your pasta is done (-1 minute), drain it and put it in the bowl with eggs. At this step you may consider the timing: if the pasta is too hot you will cook the eggs, "
                + "and some people don’t like it this way, so just wait for a minute. Keep moving and stirring to fully incorporate the eggs. Add guanciale and as many fats remaining in the pan as you want. Keep moving and stirring.").save()
    Instruction(recipe=carbonara, step_number=6, text="Plate and optionally garnish with the preferred grated cheese and black pepper. Voila.").save()

    Instruction(recipe=lavacake, step_number=1, text="Cover the baking tin with some butter.").save()
    Instruction(recipe=lavacake, step_number=2, text="Heat the oven for 200°C.").save()
    Instruction(recipe=lavacake, step_number=3, text="Mix all of the ingredients.").save()
    Instruction(recipe=lavacake, step_number=4, text="Fill dough in the baking tins pits.").save()
    Instruction(recipe=lavacake, step_number=5, text="Bake for 7 min. in the oven at 200°C.").save()
    Instruction(recipe=lavacake, step_number=6, text="Serve hot with berries and vanilla ice-cream.").save()

    Instruction(recipe=caesar, step_number=1, text="Prepare a whole head of Romaine Lettuce by chopping off the root and rising thoroughly with water. Dry completely.").save()
    Instruction(recipe=caesar, step_number=2, text="Once the lettuce is fully dry, put in a mixing bowl with lettuce and the Caesar Salad dressing. Toss to cover each leaf completely.").save()
    Instruction(recipe=caesar, step_number=3, text="Add croutons.").save()
    Instruction(recipe=caesar, step_number=4, text="Grate Parmesan over salad.").save()
    Instruction(recipe=caesar, step_number=5, text="Enjoy!").save()

def remove_recipes(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    Recipe = apps.get_model('recipes', 'Recipe')

    Ingredient.objects.all().delete()
    Recipe.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_simple_cake_recipe, remove_recipes),
    ]
