# Generated by Django 5.1 on 2024-08-20 22:56

from django.db import migrations

def create_simple_cake_recipe(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    Recipe = apps.get_model('recipes', 'Recipe')
    RecipeIngredient = apps.get_model('recipes', 'RecipeIngredient')

    # RecipeIngredient(recipe=)

    # egg = Ingredient(name="Egg")
    

    Recipe(name="Simple White Cake", description="Easy but delicious cake recipe. Top with your favorite frosting!", 
           cook_time_minutes=40, serving_size=12, instructions="These are the instructions.").save()

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_simple_cake_recipe),
    ]
